2025-04-20 19:36:12:3612 [31merror[39m: [31mError connecting to the database: no existe la base de datos ï¿½secure_authï¿½[39m
2025-04-20 19:38:40:3840 [32minfo[39m: [32mDataba connection established successfully[39m
2025-04-20 19:38:40:3840 [32minfo[39m: [32mServer is running on port 8000[39m
2025-04-20 19:38:40:3840 [32minfo[39m: [32mBase path is /api/v1[39m
